remote_theme: pages-themes/midnight
plugins: 
 - jekyll-remote-theme
title: "<a href='/public-note/'>public note</a>"
description: "A public note, written casually."
show_downloads: false
google_analytics: G-DS0WYP3WCD
